# Generated by Django 3.2.12 on 2022-03-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='login_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
