# Generated by Django 5.2.5 on 2025-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0002_credentials_login_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.TextField(),
        ),
    ]
